server:
  port: 8080

apiPrefix:
  v1: 'api/v1'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogue
    username: catalogue
    password: catalogue
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true