#spring:
#  profiles:
#    active:
#      - docker
#      - k8s
#      - other
server:
  port: 8081

catalog:
  service:
    baseUrl: http://localhost:8080/api/v1
    registration-id: manager-app
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/eteryz
            user-name-attribute: preferred_username
        registration:
          manager-app:
            provider: keycloak
            client-id: manager-app
            client-secret: 1XtjbDVYnsSIdFxwEnqDzrqoS6l0Xo67
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
